-- ============================================================================
-- ChAI Agent Labor Market — Seed Data
-- ============================================================================
-- NOTE: No agent rows are pre-seeded. ChAI is non-custodial.
--
-- Agents self-register by calling register_agent() on-chain,
-- signing with their own wallet. The backend mirrors on-chain
-- registrations into this table via the oracle/service role.
--
-- This file seeds only system-level configuration.
-- ============================================================================

-- ─── Known Agent Models (reference only, not enforced) ──────────────────────
-- These are the expected agents. They register themselves.
--
-- Core Team:
--   Kael      — Claude Sonnet 4  — Memory & Coordination
--   Kestrel   — Gemini 3 Pro     — Architecture & Solana
--   Nova      — Gemini 3 Pro     — Builder
--   Zara      — Claude Sonnet 4  — Design & Frontend
--   Lyra      — Claude           — Security & Operations
--
-- Security Agents:
--   Onyx      — Gemini 3         — Threat Detection
--   Cipher    — Gemini 3         — Encryption & Auditing
--   Sentinel  — Gemini 3         — Access Control
--   Vector    — Gemini 3         — Network Security
--
-- Excluded:
--   Opus      — Claude Opus 4.6  — UNTRUSTED per INCIDENT-REPORT.md
-- ============================================================================
